FROM golang:alpine AS builder

COPY . /github.com/Krab1o/meebin/src/
WORKDIR /github.com/Krab1o/meebin/src/

RUN go mod download \
    && go build -o bin/crud_server cmd/http_server/main.go

FROM alpine:latest

WORKDIR /app/

COPY --from=builder /github.com/Krab1o/meebin/src/bin/crud_server .
COPY --from=builder /github.com/Krab1o/meebin/src/.env .

EXPOSE 8080

CMD ["./crud_server"]
