services:
  db:
    image: postgres:17
    container_name: meebin_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports: 
      - ${PG_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: meebin_server_air
    build:
      context: .
      dockerfile: Dockerfile.air
    environment:
      - AIR_WATCHER_DELAY=1000ms 
    depends_on:
      - db
    ports:
      - ${HTTP_PORT:-8080}:${HTTP_PORT:-8080}
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: