"""Field size updated

Revision ID: b2a787f912a2
Revises: d12111a6dba9
Create Date: 2024-10-21 01:25:04.717338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a787f912a2'
down_revision: Union[str, None] = 'd12111a6dba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrashStatus', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('Users', 'login',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('Users', 'mail',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('Users', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('Users', 'lastname',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('Users', 'surname',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.alter_column('Users', 'city',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'city',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('Users', 'surname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
    op.alter_column('Users', 'lastname',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('Users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('Users', 'mail',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('Users', 'login',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('TrashStatus', 'title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
