"""Initial migration

Revision ID: d12111a6dba9
Revises: 
Create Date: 2024-10-21 00:16:57.212598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12111a6dba9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roles_id'), 'Roles', ['id'], unique=True)
    op.create_table('TrashStatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TrashStatus_id'), 'TrashStatus', ['id'], unique=True)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('lastname', sa.String(length=40), nullable=False),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('birthdate', sa.TIMESTAMP(), nullable=False),
    sa.Column('report_counter', sa.BigInteger(), nullable=False),
    sa.Column('utilized_counter', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=True)
    op.create_table('TrashEvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('caller_id', sa.BigInteger(), nullable=False),
    sa.Column('utilizator_id', sa.BigInteger(), nullable=False),
    sa.Column('event_status', sa.BigInteger(), nullable=False),
    sa.Column('time_called', sa.TIMESTAMP(), nullable=False),
    sa.Column('time_cleaned', sa.TIMESTAMP(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.Column('confirmation_photo_url', sa.String(length=255), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['event_status'], ['TrashStatus.id'], ),
    sa.ForeignKeyConstraint(['utilizator_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TrashEvent_id'), 'TrashEvent', ['id'], unique=True)
    op.create_table('Users_Roles',
    sa.Column('id_roles', sa.BigInteger(), nullable=False),
    sa.Column('id_users', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_roles'], ['Roles.id'], ),
    sa.ForeignKeyConstraint(['id_users'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id_roles', 'id_users')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users_Roles')
    op.drop_index(op.f('ix_TrashEvent_id'), table_name='TrashEvent')
    op.drop_table('TrashEvent')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_TrashStatus_id'), table_name='TrashStatus')
    op.drop_table('TrashStatus')
    op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    op.drop_table('Roles')
    # ### end Alembic commands ###
