// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Krab1o",
            "url": "https://t.me/krab1o"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Creates new pair of refresh-access tokens based on your credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Login info",
                        "name": "LoginCreds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginCreds"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseTokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Disables refresh token so you won't able to use it in /auth/refresh method",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Returns new access token based on your refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh",
                "parameters": [
                    {
                        "description": "User's Refresh Token",
                        "name": "RefreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AccessToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registers a new user in service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registration",
                "parameters": [
                    {
                        "description": "New User Info",
                        "name": "UserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseTokens"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Returns an array of events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Listing events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BaseEvent"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Creates a new event in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Creates event",
                "parameters": [
                    {
                        "description": "New Event Info",
                        "name": "EventData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.NewEvent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.IdResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/events/{event_id}": {
            "get": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Returns event by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Get event by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseEvent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Delete an event from the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Deletes event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Updates event's fields specified in the body.\nRedundant fields ignored.\nIf the field not specified, it is not updated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Updates event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Updated event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated event fields",
                        "name": "UpdatedEntity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseEvent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Returns an array of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Listing users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.BaseUser"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Returns user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Deletes user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Deletes user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "jwtToken": []
                    }
                ],
                "description": "Updates user's fields specified in the body.\nRedundant fields ignored.\nIf the field not specified, it is not updated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Updates user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Updated user ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated user fields",
                        "name": "UpdatedEntity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Error": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "dto.AccessToken": {
            "type": "object",
            "required": [
                "accessToken"
            ],
            "properties": {
                "accessToken": {
                    "description": "Should be a JWT access-token",
                    "type": "string"
                }
            }
        },
        "dto.BaseCreds": {
            "description": "BaseUser credentials",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user123@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 8,
                    "example": "Password123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "user123"
                }
            }
        },
        "dto.BaseEvent": {
            "type": "object",
            "required": [
                "data",
                "id",
                "status"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.BaseEventData"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "status": {
                    "$ref": "#/definitions/model.EventStatus"
                }
            }
        },
        "dto.BaseEventData": {
            "type": "object",
            "required": [
                "caller_id",
                "description",
                "latitude",
                "longtitude",
                "time_called",
                "title"
            ],
            "properties": {
                "caller_id": {
                    "type": "integer",
                    "example": 42
                },
                "description": {
                    "type": "string",
                    "example": "Бла-бла-бла"
                },
                "latitude": {
                    "type": "number",
                    "example": 42.881
                },
                "longtitude": {
                    "type": "number",
                    "example": 45.254
                },
                "time_called": {
                    "type": "string",
                    "format": "date-time"
                },
                "time_utilized": {
                    "type": "string",
                    "format": "date-time"
                },
                "title": {
                    "type": "string",
                    "example": "Ужасное загрязнение"
                },
                "utilizator_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "dto.BasePersonalData": {
            "description": "BaseUser personal data",
            "type": "object",
            "properties": {
                "birthDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "city": {
                    "type": "string",
                    "example": "Vladivostok"
                },
                "givenName": {
                    "type": "string",
                    "example": "Ivan"
                },
                "patronymic": {
                    "type": "string",
                    "example": "Ivanovich"
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.BaseStats": {
            "description": "BaseUser statistics",
            "type": "object",
            "properties": {
                "rating": {
                    "type": "number"
                },
                "reportCount": {
                    "type": "integer"
                },
                "utilizeCount": {
                    "type": "integer"
                }
            }
        },
        "dto.BaseUser": {
            "description": "BaseUser-part of a list-of-users requests",
            "type": "object",
            "properties": {
                "creds": {
                    "$ref": "#/definitions/dto.BaseCreds"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "personalData": {
                    "$ref": "#/definitions/dto.BasePersonalData"
                },
                "roles": {
                    "description": "Roles' array",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/dto.BaseStats"
                }
            }
        },
        "dto.IdResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "dto.LoginCreds": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user123@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 8,
                    "example": "Password123"
                }
            }
        },
        "dto.NewEvent": {
            "type": "object",
            "required": [
                "data",
                "id"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.NewEventData"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "dto.NewEventData": {
            "type": "object",
            "required": [
                "description",
                "latitude",
                "longtitude",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Бла-бла-бла"
                },
                "latitude": {
                    "type": "number",
                    "example": 42.881
                },
                "longtitude": {
                    "type": "number",
                    "example": 45.254
                },
                "title": {
                    "type": "string",
                    "example": "Ужасное загрязнение"
                }
            }
        },
        "dto.RefreshToken": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "description": "Should be a JWT refresh-token",
                    "type": "string"
                }
            }
        },
        "dto.RegisterCreds": {
            "description": "New user's credentials",
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user123@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 8,
                    "example": "Password123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "user123"
                }
            }
        },
        "dto.RegisterPersonalData": {
            "description": "New user's personal data",
            "type": "object",
            "required": [
                "birthDate",
                "city",
                "givenName",
                "patronymic",
                "surname"
            ],
            "properties": {
                "birthDate": {
                    "description": "This field accepts default time format from RFC (DD-MM-YYYY, just pick default time library)",
                    "type": "string",
                    "format": "date-time"
                },
                "city": {
                    "type": "string",
                    "example": "Vladivostok"
                },
                "givenName": {
                    "type": "string",
                    "example": "Ivan"
                },
                "patronymic": {
                    "type": "string",
                    "example": "Ivanovich"
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.RegisterUser": {
            "description": "New registrating user structure",
            "type": "object",
            "required": [
                "creds",
                "personalData"
            ],
            "properties": {
                "creds": {
                    "$ref": "#/definitions/dto.RegisterCreds"
                },
                "personalData": {
                    "$ref": "#/definitions/dto.RegisterPersonalData"
                }
            }
        },
        "dto.ResponseTokens": {
            "type": "object",
            "required": [
                "accessToken",
                "refreshToken"
            ],
            "properties": {
                "accessToken": {
                    "description": "Should be a JWT access-token",
                    "type": "string"
                },
                "refreshToken": {
                    "description": "Should be a JWT refresh-token",
                    "type": "string"
                }
            }
        },
        "dto.UpdateCreds": {
            "description": "Credentials which will be updated",
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user123@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "minLength": 8,
                    "example": "Password123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "user123"
                }
            }
        },
        "dto.UpdateEvent": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.UpdateEventData"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "status": {
                    "$ref": "#/definitions/model.EventStatus"
                }
            }
        },
        "dto.UpdateEventData": {
            "type": "object",
            "properties": {
                "caller_id": {
                    "type": "integer",
                    "example": 42
                },
                "description": {
                    "type": "string",
                    "example": "Бла-бла-бла"
                },
                "latitude": {
                    "type": "number",
                    "example": 42.881
                },
                "longtitude": {
                    "type": "number",
                    "example": 45.254
                },
                "time_called": {
                    "type": "string",
                    "format": "date-time"
                },
                "time_utilized": {
                    "type": "string",
                    "format": "date-time"
                },
                "title": {
                    "type": "string",
                    "example": "Ужасное загрязнение"
                },
                "utilizator_id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "dto.UpdatePersonalData": {
            "description": "Personal data which will be updated",
            "type": "object",
            "properties": {
                "birthDate": {
                    "description": "This field accepts default time format from RFC (DD-MM-YYYY, just pick default time library)",
                    "type": "string",
                    "format": "date"
                },
                "city": {
                    "type": "string",
                    "example": "Vladivostok"
                },
                "givenName": {
                    "type": "string",
                    "example": "Ivan"
                },
                "patronymic": {
                    "type": "string",
                    "example": "Ivanovich"
                },
                "surname": {
                    "type": "string",
                    "example": "Ivanov"
                }
            }
        },
        "dto.UpdateUser": {
            "description": "Entity which will be updated",
            "type": "object",
            "properties": {
                "creds": {
                    "$ref": "#/definitions/dto.UpdateCreds"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "personalData": {
                    "$ref": "#/definitions/dto.UpdatePersonalData"
                }
            }
        },
        "model.EventStatus": {
            "type": "integer",
            "enum": [
                1
            ],
            "x-enum-varnames": [
                "StatusOnModeration"
            ]
        }
    },
    "securityDefinitions": {
        "jwtToken": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Everything linked with authorization and JWT-token control",
            "name": "Auth"
        },
        {
            "description": "User control API",
            "name": "User"
        },
        {
            "description": "Event control API",
            "name": "Event"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Meebin",
	Description:      "API for Meebin application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
